# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9964bdabbdcbfa04332daba6ed3496fc83ad8b9bc1d10034332d4057611722ee0bf9befcd1fd05ac67936dc5086ddace489a580aa418b4df3163b816611661bc

test:
  secret_key_base: 5fe5ef7002f42aa1c8e585566127dce77aa5d776d484ef2f57a1d9faa592b6f30dcfb2079d0151a27e068d249cea2d67df45c696fe8352c5c46d4be07f97f3ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
